import { AlertTriangle, CheckCircle2, Database, FileDiff, LockKeyhole } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import type { FieldDiff, ProviderSnapshotRecord } from "@/lib/data/provider-diffs";
import { formatKoreaDateTime } from "@/lib/format";
import { cn } from "@/lib/utils";

export function DataDiffPanel({ fields, snapshot, error }: { fields: FieldDiff[]; snapshot: ProviderSnapshotRecord | null; error: string | null }) {
  const differences = fields.filter((field) => field.different);
  return <section className="overflow-hidden rounded-xl border border-border/80 bg-card/40"><div className="flex flex-wrap items-start justify-between gap-3 border-b border-border/70 px-4 py-3"><div className="flex items-start gap-2"><FileDiff className="mt-0.5 size-4 text-muted-foreground" /><div><h2 className="text-sm font-semibold">현재 앱 값과 외부 데이터 비교</h2><p className="mt-0.5 text-[11px] text-muted-foreground">이름, 상태, 점수처럼 운영자가 확인할 수 있는 항목만 비교합니다.</p></div></div>{snapshot ? <div className="text-right"><Badge variant="outline"><Database className="size-3" /> 외부 데이터 연결됨</Badge><p className="mt-1 text-[10px] text-muted-foreground">가져온 시각 {formatKoreaDateTime(snapshot.fetchedAt)}</p></div> : null}</div>
    {error ? <div className="flex items-start gap-2 border-b border-amber-400/15 bg-amber-400/[0.05] px-4 py-3 text-xs text-amber-100/75"><AlertTriangle className="mt-0.5 size-4 shrink-0 text-amber-300" />{error}</div> : null}
    {!snapshot ? <div className="flex min-h-48 flex-col items-center justify-center px-4 text-center"><Database className="size-5 text-muted-foreground" /><p className="mt-3 text-sm font-medium">비교할 외부 데이터가 없습니다</p><p className="mt-1 max-w-md text-xs leading-5 text-muted-foreground">데이터 새로고침으로 외부 값을 가져오면 현재 앱 값과 차이를 확인할 수 있습니다.</p></div> : <><div className="overflow-x-auto"><Table><TableHeader><TableRow className="hover:bg-transparent"><TableHead>항목</TableHead><TableHead>현재 앱 값</TableHead><TableHead>외부 최신값</TableHead><TableHead>확인 결과</TableHead></TableRow></TableHeader><TableBody>{fields.map((field) => <TableRow key={field.field} className={cn(field.different && "bg-amber-400/[0.035]")}><TableCell><p className="text-xs font-medium">{field.label}</p></TableCell><TableCell className="max-w-64 break-all font-mono text-xs">{show(field.databaseValue)}</TableCell><TableCell className="max-w-64 break-all font-mono text-xs">{show(field.providerValue)}</TableCell><TableCell>{field.protectedByOverride ? <Badge variant="outline" className="border-primary/25 text-primary"><LockKeyhole className="size-3" /> 직접 수정값 보호 중</Badge> : field.different ? <Badge variant="outline" className="border-amber-400/25 text-amber-200">확인 필요</Badge> : <Badge variant="outline" className="border-emerald-400/20 text-emerald-200"><CheckCircle2 className="size-3" /> 일치</Badge>}</TableCell></TableRow>)}</TableBody></Table></div><div className="flex flex-wrap items-center gap-3 border-t border-border/70 px-4 py-3 text-xs text-muted-foreground"><span>비교 항목 {fields.length}개</span><strong className={differences.length > 0 ? "text-amber-200" : "text-emerald-200"}>확인 필요 {differences.length}개</strong><details className="ml-auto"><summary className="cursor-pointer text-primary">개발자용 원본 정보</summary><div className="mt-2 max-w-3xl rounded-md bg-background p-3"><dl className="mb-3 grid gap-2 text-[10px] sm:grid-cols-2"><div><dt className="text-muted-foreground">제공처</dt><dd className="mt-0.5 font-mono">{snapshot.provider}</dd></div><div><dt className="text-muted-foreground">요청 경로</dt><dd className="mt-0.5 break-all font-mono">{snapshot.sourceEndpoint ?? "확인 불가"}</dd></div></dl><pre className="max-h-80 overflow-auto font-mono text-[10px] leading-4 text-muted-foreground">{JSON.stringify(snapshot.rawPayload, null, 2).slice(0, 20_000)}</pre></div></details></div></>}
  </section>;
}

function show(value: unknown) { return value === null || value === undefined ? "없음" : typeof value === "string" ? value : JSON.stringify(value); }
