-- Remove only data that is unambiguously generated by local QA or E2E runs.
-- Real provider fixtures, historical records, and existing user accounts stay.
delete from public.notifications
where title = '🔔 앱 실행 중 알림 테스트'
   or dedupe_key like 'manual-test:%'
   or data ->> 'test' = 'true';

delete from public.posts
where title ilike 'E2E %';

delete from public.fixture_cheer_messages
where content = 'E2E matchday cheer';

delete from public.support_inquiries
where subject ilike 'E2E %'
   or content ilike '%E2E support inquiry%';

delete from public.fixtures
where id like 'dev-%'
   or id like 'e2e-%'
   or id in (
     'fixture-today',
     'fixture-next',
     'fixture-later',
     'fixture-finished-win',
     'fixture-finished-loss',
     'fixture-finished-draw'
   );

delete from public.player_scoring_stats
where player_id ~ '^(incheon|seoul|jeonbuk|ulsan|daejeon|pohang|anyang|bucheon|gangwon|jeju|gwangju|gimcheon)-';

delete from auth.users
where email like 'kickon-e2e-%@example.com';

-- A deletion cooldown retains only a one-way hash of the external identity.
-- No email address, provider subject, user UUID, or profile data is retained.
create table public.account_rejoin_cooldowns (
  identity_hash text primary key check (
    identity_hash ~ '^[0-9a-f]{64}$'
  ),
  provider text not null check (char_length(provider) between 1 and 50),
  deleted_at timestamptz not null default now(),
  blocked_until timestamptz not null,
  constraint account_rejoin_cooldowns_window_check
    check (blocked_until > deleted_at)
);

create index account_rejoin_cooldowns_blocked_until_idx
  on public.account_rejoin_cooldowns (blocked_until);

alter table public.account_rejoin_cooldowns enable row level security;
revoke all on public.account_rejoin_cooldowns from public, anon, authenticated;
grant select, insert, update, delete
  on public.account_rejoin_cooldowns to service_role;

create or replace function public.account_identity_hash(
  provider_name text,
  provider_subject text
)
returns text
language sql
immutable
strict
parallel safe
set search_path = ''
as $$
  select encode(
    extensions.digest(
      lower(trim(provider_name)) || ':' || trim(provider_subject),
      'sha256'
    ),
    'hex'
  );
$$;

revoke all on function public.account_identity_hash(text, text) from public;
grant execute on function public.account_identity_hash(text, text)
  to service_role;

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  provider_name text := lower(nullif(
    trim(coalesce(new.raw_app_meta_data ->> 'provider', '')),
    ''
  ));
  provider_subject text := nullif(
    trim(coalesce(
      new.raw_user_meta_data ->> 'sub',
      new.raw_user_meta_data ->> 'provider_id',
      ''
    )),
    ''
  );
  normalized_email text := nullif(lower(trim(coalesce(new.email, ''))), '');
  active_block_until timestamptz;
begin
  delete from public.account_rejoin_cooldowns
  where blocked_until <= now();

  select max(cooldown.blocked_until)
  into active_block_until
  from public.account_rejoin_cooldowns cooldown
  where cooldown.blocked_until > now()
    and cooldown.identity_hash in (
      public.account_identity_hash(provider_name, provider_subject),
      public.account_identity_hash('email', normalized_email)
    );

  if active_block_until is not null then
    raise exception 'REJOIN_COOLDOWN_ACTIVE'
      using detail = active_block_until::text;
  end if;

  insert into public.profiles (id, nickname)
  values (new.id, '');
  insert into public.notification_preferences (user_id)
  values (new.id);
  return new;
end;
$$;

comment on table public.account_rejoin_cooldowns is
  'One-way identity hashes retained for seven days after account deletion to enforce the rejoin cooldown.';
comment on function public.account_identity_hash(text, text) is
  'Produces the canonical one-way identity hash used by account deletion and signup checks.';
