begin;

-- 관리자 기본 계약이 적용된 프로젝트에 감사 로그만 독립적으로 추가합니다.
do $$
begin
  if to_regtype('public.admin_role') is null
    or to_regclass('public.admin_users') is null
    or to_regprocedure('public.admin_has_capability(text)') is null
  then
    raise exception 'ADMIN_BASE_SCHEMA_REQUIRED';
  end if;
end
$$;

create table if not exists public.admin_audit_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id) on delete set null,
  actor_role public.admin_role,
  action text not null,
  entity_type text not null,
  entity_id text,
  reason text,
  before_value jsonb,
  after_value jsonb,
  request_id text,
  ip_hash text,
  created_at timestamptz not null default now()
);

alter table public.admin_audit_logs
  add column if not exists actor_id uuid references auth.users(id) on delete set null,
  add column if not exists actor_role public.admin_role,
  add column if not exists action text,
  add column if not exists entity_type text,
  add column if not exists entity_id text,
  add column if not exists reason text,
  add column if not exists before_value jsonb,
  add column if not exists after_value jsonb,
  add column if not exists request_id text,
  add column if not exists ip_hash text,
  add column if not exists created_at timestamptz not null default now();

create index if not exists admin_audit_logs_entity_idx
  on public.admin_audit_logs (entity_type, entity_id, created_at desc);
create index if not exists admin_audit_logs_actor_idx
  on public.admin_audit_logs (actor_id, created_at desc);

-- 운영 RPC에서 명시적으로 감사 기록을 남길 때 사용하는 공통 함수입니다.
create or replace function public.data_center_write_audit(
  p_action text,
  p_target_type text,
  p_target_id text,
  p_before_data jsonb,
  p_after_data jsonb,
  p_reason text
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_actor uuid := (select auth.uid());
  current_role public.admin_role;
begin
  select administrator.role
  into current_role
  from public.admin_users administrator
  where administrator.user_id = current_actor
    and administrator.is_active;

  insert into public.admin_audit_logs (
    actor_id, actor_role, action, entity_type, entity_id, reason,
    before_value, after_value
  ) values (
    current_actor,
    current_role,
    left(coalesce(nullif(trim(p_action), ''), 'UNKNOWN'), 120),
    left(coalesce(nullif(trim(p_target_type), ''), 'unknown'), 120),
    nullif(left(coalesce(p_target_id, ''), 300), ''),
    nullif(left(trim(coalesce(p_reason, '')), 1000), ''),
    p_before_data,
    p_after_data
  );
end;
$$;

-- 직접 수정 테이블 변경도 빠짐없이 기록합니다.
create or replace function public.record_admin_audit_log()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  row_data jsonb;
  row_id text;
  audit_reason text;
  audit_action text;
begin
  row_data := case when tg_op = 'DELETE' then to_jsonb(old) else to_jsonb(new) end;
  row_id := coalesce(
    row_data ->> 'entity_id',
    row_data ->> 'player_id',
    row_data ->> 'user_id',
    row_data ->> 'id'
  );
  audit_reason := coalesce(
    row_data ->> 'release_reason',
    row_data ->> 'resolution_note',
    row_data ->> 'reason'
  );
  audit_action := case
    when tg_table_name = 'sync_runs' and tg_op = 'INSERT'
      then 'SYNC_RUN_EXECUTE'
    else tg_op
  end;

  perform public.data_center_write_audit(
    audit_action,
    tg_table_name,
    row_id,
    case when tg_op = 'INSERT' then null else to_jsonb(old) end,
    case when tg_op = 'DELETE' then null else to_jsonb(new) end,
    audit_reason
  );

  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

do $$
begin
  if to_regclass('public.manual_overrides') is not null
    and not exists (
      select 1
      from pg_trigger trigger_record
      join pg_proc trigger_function
        on trigger_function.oid = trigger_record.tgfoid
      where trigger_record.tgrelid = 'public.manual_overrides'::regclass
        and not trigger_record.tgisinternal
        and trigger_function.proname in (
          'record_admin_audit_log', 'data_center_record_table_audit'
        )
    )
  then
    create trigger manual_overrides_audit
      after insert or update or delete on public.manual_overrides
      for each row execute function public.record_admin_audit_log();
  end if;
end
$$;

do $$
begin
  if to_regclass('public.sync_runs') is not null
    and not exists (
      select 1
      from pg_trigger trigger_record
      join pg_proc trigger_function
        on trigger_function.oid = trigger_record.tgfoid
      where trigger_record.tgrelid = 'public.sync_runs'::regclass
        and not trigger_record.tgisinternal
        and trigger_function.proname in (
          'record_admin_audit_log', 'data_center_record_table_audit'
        )
    )
  then
    create trigger sync_runs_audit
      after insert on public.sync_runs
      for each row execute function public.record_admin_audit_log();
  end if;
end
$$;

-- 트리거 연결 전에 실행된 수동 동기화 기록도 한 번만 가져옵니다.
do $$
begin
  if to_regclass('public.sync_runs') is not null then
    execute $backfill$
      insert into public.admin_audit_logs (
        actor_id, actor_role, action, entity_type, entity_id, reason,
        before_value, after_value, created_at
      )
      select
        run.requested_by,
        administrator.role,
        'SYNC_RUN_EXECUTE',
        'sync_runs',
        run.id::text,
        run.reason,
        null,
        to_jsonb(run),
        coalesce(run.started_at, run.created_at)
      from public.sync_runs run
      left join public.admin_users administrator
        on administrator.user_id = run.requested_by
      where run.trigger_type = 'manual'
        and not exists (
          select 1
          from public.admin_audit_logs audit
          where audit.entity_type = 'sync_runs'
            and audit.entity_id = run.id::text
            and audit.action = 'SYNC_RUN_EXECUTE'
        )
    $backfill$;
  end if;
end
$$;

alter table public.admin_audit_logs enable row level security;

drop policy if exists "data center operators read audit logs"
  on public.admin_audit_logs;
drop policy if exists "data center super admins read audit logs"
  on public.admin_audit_logs;
create policy "data center operators read audit logs"
  on public.admin_audit_logs for select to authenticated
  using (public.admin_has_capability('audit.read'));

revoke all on table public.admin_audit_logs from public, anon;
grant select on table public.admin_audit_logs to authenticated;
grant all on table public.admin_audit_logs to service_role;
grant usage, select on sequence public.admin_audit_logs_id_seq
  to service_role;

revoke all on function public.data_center_write_audit(
  text, text, text, jsonb, jsonb, text
) from public, anon, authenticated;
revoke all on function public.record_admin_audit_log()
  from public, anon, authenticated;

commit;

notify pgrst, 'reload schema';

select
  to_regclass('public.admin_audit_logs') is not null as audit_table_ready,
  to_regprocedure(
    'public.data_center_write_audit(text,text,text,jsonb,jsonb,text)'
  ) is not null as audit_writer_ready;
