begin;

-- Partially initialized production projects may already have admin_users and
-- admin_has_capability, while the legacy operations tables are still absent.
-- This bootstrap creates only the prerequisites required by
-- 202608300002_player_operations.sql and 202608300003_provider_snapshots.sql.

do $$
begin
  if to_regtype('public.report_status') is null then
    create type public.report_status as enum (
      'open', 'in_review', 'resolved', 'rejected', 'on_hold'
    );
  end if;
  if to_regtype('public.report_priority') is null then
    create type public.report_priority as enum (
      'low', 'normal', 'high', 'urgent'
    );
  end if;
  if to_regtype('public.sync_run_status') is null then
    create type public.sync_run_status as enum (
      'queued', 'running', 'succeeded', 'partial', 'failed', 'cancelled'
    );
  end if;
end
$$;

-- Compatibility contract used by the older player/provider migrations.
-- The current authorization source remains admin_users.
create or replace function public.is_admin(required_role text default 'viewer')
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.admin_users administrator
    where administrator.user_id = (select auth.uid())
      and administrator.is_active
      and case administrator.role::text
        when 'viewer' then 10
        when 'support' then 10
        when 'operator' then 20
        when 'moderator' then 20
        when 'data_editor' then 30
        when 'admin' then 30
        when 'super_admin' then 40
        else 0
      end >= case lower(coalesce(required_role, 'viewer'))
        when 'viewer' then 10
        when 'operator' then 20
        when 'admin' then 30
        when 'super_admin' then 40
        else 100
      end
  );
$$;

revoke all on function public.is_admin(text) from public, anon;
grant execute on function public.is_admin(text) to authenticated, service_role;

create table if not exists public.user_data_reports (
  id uuid primary key default gen_random_uuid(),
  reporter_id uuid not null references auth.users(id) on delete cascade,
  entity_type text not null check (
    entity_type in ('team', 'player', 'fixture', 'standing', 'ranking', 'other')
  ),
  entity_id text,
  field_path text,
  current_value jsonb,
  proposed_value jsonb,
  description text not null check (char_length(description) between 3 and 4000),
  evidence_urls text[] not null default '{}',
  status public.report_status not null default 'open',
  priority public.report_priority not null default 'normal',
  assignee_id uuid references public.admin_users(user_id) on delete set null,
  resolution_note text,
  resolved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.user_data_report_history (
  id bigint generated by default as identity primary key,
  report_id uuid not null references public.user_data_reports(id) on delete cascade,
  from_status public.report_status,
  to_status public.report_status not null,
  note text,
  changed_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.sync_runs (
  id uuid primary key default gen_random_uuid(),
  job_key text not null,
  target_type text,
  target_id text,
  trigger_type text not null check (
    trigger_type in ('cron', 'manual', 'webhook', 'retry', 'system')
  ),
  environment text not null check (environment in ('development', 'production')),
  status public.sync_run_status not null default 'queued',
  requested_by uuid references public.admin_users(user_id) on delete set null,
  reason text,
  started_at timestamptz,
  finished_at timestamptz,
  inserted_count integer check (inserted_count is null or inserted_count >= 0),
  updated_count integer check (updated_count is null or updated_count >= 0),
  skipped_count integer check (skipped_count is null or skipped_count >= 0),
  failed_count integer check (failed_count is null or failed_count >= 0),
  provider_request_count integer check (
    provider_request_count is null or provider_request_count >= 0
  ),
  error_code text,
  error_message text,
  metadata jsonb not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.manual_overrides (
  id uuid primary key default gen_random_uuid(),
  entity_type text not null check (
    entity_type in ('team', 'player', 'fixture', 'standing', 'ranking')
  ),
  entity_id text not null,
  field_path text not null,
  original_value jsonb,
  override_value jsonb not null,
  reason text not null check (char_length(reason) between 3 and 1000),
  blocks_sync boolean not null default false,
  created_by uuid not null references public.admin_users(user_id) on delete restrict,
  released_by uuid references public.admin_users(user_id) on delete set null,
  released_at timestamptz,
  release_reason text,
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check ((released_at is null and released_by is null) or released_at is not null)
);

create table if not exists public.admin_audit_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id) on delete set null,
  actor_role public.admin_role,
  action text not null,
  entity_type text not null,
  entity_id text,
  reason text,
  before_value jsonb,
  after_value jsonb,
  request_id text,
  ip_hash text,
  created_at timestamptz not null default now()
);

create index if not exists user_data_reports_queue_idx
  on public.user_data_reports (status, priority, created_at desc);
create index if not exists user_data_reports_reporter_idx
  on public.user_data_reports (reporter_id, created_at desc);
create index if not exists user_data_report_history_report_idx
  on public.user_data_report_history (report_id, created_at desc);
create index if not exists sync_runs_job_created_idx
  on public.sync_runs (job_key, created_at desc);
create index if not exists sync_runs_status_created_idx
  on public.sync_runs (status, created_at desc);
create index if not exists manual_overrides_entity_idx
  on public.manual_overrides (entity_type, entity_id, created_at desc);
create index if not exists admin_audit_logs_entity_idx
  on public.admin_audit_logs (entity_type, entity_id, created_at desc);

create or replace function public.set_admin_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists user_data_reports_set_updated_at
  on public.user_data_reports;
create trigger user_data_reports_set_updated_at
  before update on public.user_data_reports
  for each row execute function public.set_admin_updated_at();

drop trigger if exists sync_runs_set_updated_at on public.sync_runs;
create trigger sync_runs_set_updated_at
  before update on public.sync_runs
  for each row execute function public.set_admin_updated_at();

drop trigger if exists manual_overrides_set_updated_at
  on public.manual_overrides;
create trigger manual_overrides_set_updated_at
  before update on public.manual_overrides
  for each row execute function public.set_admin_updated_at();

create or replace function public.record_admin_audit_log()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_actor uuid := (select auth.uid());
  current_role public.admin_role;
  row_id text;
  audit_reason text;
begin
  select administrator.role
  into current_role
  from public.admin_users administrator
  where administrator.user_id = current_actor;

  if tg_table_name = 'manual_overrides' then
    row_id := coalesce(to_jsonb(new)->>'entity_id', to_jsonb(old)->>'entity_id');
  elsif tg_table_name = 'player_change_events' then
    row_id := coalesce(to_jsonb(new)->>'player_id', to_jsonb(old)->>'player_id');
  else
    row_id := coalesce(to_jsonb(new)->>'id', to_jsonb(old)->>'id');
  end if;
  audit_reason := coalesce(
    to_jsonb(new)->>'release_reason',
    to_jsonb(new)->>'resolution_note',
    to_jsonb(new)->>'reason'
  );

  insert into public.admin_audit_logs (
    actor_id, actor_role, action, entity_type, entity_id, reason,
    before_value, after_value
  ) values (
    current_actor, current_role, tg_op, tg_table_name, row_id, audit_reason,
    case when tg_op = 'INSERT' then null else to_jsonb(old) end,
    case when tg_op = 'DELETE' then null else to_jsonb(new) end
  );

  if tg_op = 'DELETE' then return old; end if;
  return new;
end;
$$;

alter table public.user_data_reports enable row level security;
alter table public.user_data_report_history enable row level security;
alter table public.sync_runs enable row level security;
alter table public.manual_overrides enable row level security;
alter table public.admin_audit_logs enable row level security;

drop policy if exists "data center users create own data reports"
  on public.user_data_reports;
create policy "data center users create own data reports"
  on public.user_data_reports for insert to authenticated
  with check (reporter_id = (select auth.uid()));

drop policy if exists "data center operators read data reports"
  on public.user_data_reports;
create policy "data center operators read data reports"
  on public.user_data_reports for select to authenticated
  using (
    reporter_id = (select auth.uid())
    or public.admin_has_capability('support.read')
    or public.admin_has_capability('data.read')
  );

drop policy if exists "data center operators update data reports"
  on public.user_data_reports;
create policy "data center operators update data reports"
  on public.user_data_reports for update to authenticated
  using (
    public.admin_has_capability('support.write')
    or public.admin_has_capability('data.write')
  )
  with check (
    public.admin_has_capability('support.write')
    or public.admin_has_capability('data.write')
  );

drop policy if exists "data center operators read report history"
  on public.user_data_report_history;
create policy "data center operators read report history"
  on public.user_data_report_history for select to authenticated
  using (
    public.admin_has_capability('support.read')
    or public.admin_has_capability('data.read')
  );

drop policy if exists "data center operators read sync runs"
  on public.sync_runs;
create policy "data center operators read sync runs"
  on public.sync_runs for select to authenticated
  using (
    public.admin_has_capability('sync.read')
    or public.admin_has_capability('system.read')
  );

drop policy if exists "data center operators create sync runs"
  on public.sync_runs;
create policy "data center operators create sync runs"
  on public.sync_runs for insert to authenticated
  with check (
    public.admin_has_capability('sync.run')
    and requested_by = (select auth.uid())
  );

drop policy if exists "data center operators update sync runs"
  on public.sync_runs;
create policy "data center operators update sync runs"
  on public.sync_runs for update to authenticated
  using (public.admin_has_capability('sync.run'))
  with check (public.admin_has_capability('sync.run'));

drop policy if exists "data center operators read overrides"
  on public.manual_overrides;
create policy "data center operators read overrides"
  on public.manual_overrides for select to authenticated
  using (public.admin_has_capability('data.read'));

drop policy if exists "data center operators read audit logs"
  on public.admin_audit_logs;
create policy "data center operators read audit logs"
  on public.admin_audit_logs for select to authenticated
  using (public.admin_has_capability('audit.read'));

revoke all on table public.user_data_reports,
  public.user_data_report_history, public.sync_runs, public.manual_overrides,
  public.admin_audit_logs from public, anon;
grant select, insert, update on table public.user_data_reports to authenticated;
grant select on table public.user_data_report_history to authenticated;
grant select, insert, update on table public.sync_runs to authenticated;
grant select on table public.manual_overrides to authenticated;
grant select on table public.admin_audit_logs to authenticated;
grant all on table public.user_data_reports, public.user_data_report_history,
  public.sync_runs, public.manual_overrides, public.admin_audit_logs
  to service_role;
grant usage, select on sequence public.user_data_report_history_id_seq,
  public.admin_audit_logs_id_seq to service_role;

commit;
